<?php 
	// Exit if access directly
	if (!defined('ABSPATH')) exit; 

/**
 * The page that handles comments. See skeleton_comment in functions.php
 *
 * The comments are generated by a callback function skeleton_comment which can
 * be found in functions.php
 *
 * @package WordPress
 * @subpackage skeleton_wordpress
 * @since 1.0
 */
?>